--Bronze
CREATE OR REPLACE TABLE azdb_sales_store.linio.bronze_compras (
    venta_id STRING,
    factura STRING,
    fecha_orden STRING,
    fecha_entrega STRING,
    fecha_envio STRING,
    estado STRING,
    cliente_code STRING,
    tipo_cliente STRING,
    nombres STRING,
    apellidos STRING,
    vendedor STRING,
    departamento STRING,
    metodo_pago STRING,
    subtotal STRING,
    tipo_compra STRING,
    fecha_carga TIMESTAMP
)
USING DELTA
LOCATION 'abfss://sales-store@azdlssalesstore.dfs.core.windows.net/bronze/compras';




CREATE OR REPLACE TABLE azdb_sales_store.linio.bronze_detalles (
    detalle_id STRING,
    factura STRING,
    categoria STRING,
    subcategoria STRING,
    producto_id STRING,
    producto STRING,
    unidades STRING,
    precio_unitario STRING,
    nombre_archivo STRING,
    fecha_carga TIMESTAMP
)
USING delta
LOCATION 'abfss://sales-store@azdlssalesstore.dfs.core.windows.net/bronze/detalles';


--Silver
CREATE OR REPLACE TABLE azdb_sales_store.linio.silver_compras (
    venta_id        INTEGER,
    factura         STRING,
    tipo_compra     STRING,
    fecha_orden     DATE,
    fecha_entrega   DATE,
    fecha_envio     DATE,
    estado          STRING,
    cliente_id      INTEGER,
    vendedor        STRING,
    departamento    STRING,
    metodo_pago     STRING,
    dias_envio      INTEGER,
    grupo_dias_envio STRING,
    periodo         DATE,
    fecha_actualizacion    TIMESTAMP
) 
USING DELTA 
PARTITIONED BY (periodo)
LOCATION 'abfss://sales-store@azdlssalesstore.dfs.core.windows.net/silver/compras';


CREATE OR REPLACE TABLE azdb_sales_store.linio.silver_clientes (
    cliente_id      INTEGER,
    tipo_documento         STRING, 
    num_documento       STRING,
    nombre_completo    STRING,
    tipo_cliente     STRING,
    fecha_actualizacion        TIMESTAMP
)
USING DELTA 
LOCATION 'abfss://sales-store@azdlssalesstore.dfs.core.windows.net/silver/clientes';




CREATE TABLE IF NOT EXISTS azdb_sales_store.linio.silver_productos (
    producto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto STRING,
    categoria STRING,
    subcategoria STRING,
    fecha_actualizacion TIMESTAMP
)
USING DELTA 
LOCATION 'abfss://sales-store@azdlssalesstore.dfs.core.windows.net/silver/productos';


CREATE OR REPLACE TABLE azdb_sales_store.linio.silver_detalles(
detalle_id  integer,
factura string ,
producto string ,
producto_id long ,
unidades integer ,
precio_unitario double,
Subtotal double ,
fecha_actualizacion timestamp 
)
USING DELTA 
LOCATION 'abfss://sales-store@azdlssalesstore.dfs.core.windows.net/silver/detalles';


-- CAPA GOLDEN
CREATE OR REPLACE VIEW linio.gold_dim_clientes AS
SELECT cliente_id, tipo_documento, num_documento, nombre_completo, tipo_cliente
FROM linio.silver_clientes;


CREATE OR REPLACE VIEW linio.gold_dim_productos AS
SELECT 
producto_id,
producto,
categoria,
subcategoria
FROM linio.silver_productos;

-- Se ha creado la tabla gold_fact_compras
CREATE OR REPLACE TABLE linio.gold_fact_compras(
 periodo date ,
 venta_id integer ,
 factura string ,
 tipo_compra string,
 fecha_orden date ,
 fecha_entrega date,
 fecha_envio date ,
 estado string ,
 cliente_id integer ,
 vendedor string ,
 departamento string ,
 metodo_pago string ,
 grupo_dias_envio string ,
 detalle_id integer ,
 producto_id long ,
 unidades integer ,
 Subtotal double ,
 fecha_actualizacion timestamp 
)
USING DELTA
PARTITIONED BY (periodo)
LOCATION 'abfss://sales-store@azdlssalesstore.dfs.core.windows.net/gold/fact_compras';


-- fin